version: '3'
services:
  minio_storage:
    container_name: minio_service
    image: quay.io/minio/minio:RELEASE.2022-02-18T01-50-10Z
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=username  #edit here
      - MINIO_ROOT_PASSWORD=password  #edit here
    volumes:
      - ./minio_service:/data